{
 "title": "MongoDB Profiler Exporter",
 "description": "Mongo DB Profiler Prometheus Exporter. Check https://github.com/andrii29/mongodb-profiler-exporter for additional info",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(slow_queries_info, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(slow_queries_count_total, instance)"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(slow_queries_count_total{job=~\"$job\", instance=~\"$instance\"}, db)"
    }
   },
   {
    "name": "ns",
    "query": {
     "query": "label_values(slow_queries_count_total{job=~\"$job\",  instance=~\"$instance\", db=~\"$db\"}, ns)"
    }
   },
   {
    "name": "query_hash",
    "query": {
     "query": "label_values(slow_queries_count_total{job=~\"$job\",  instance=~\"$instance\", db=~\"$db\", ns=~\"$ns\"}, query_hash)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slow Queries",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(slow_queries_count_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[$__range])) by (query_hash, ns) * on (query_hash, ns) group_left(op, plan_summary, query_framework, query_shape) topk(1, max_over_time(slow_queries_info[$__range])) by (query_hash)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(slow_queries_duration_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[$__range])/rate(slow_queries_count_total{job=~\"$job\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[$__range])) by (query_hash, ns) * on (query_hash, ns) group_left(op, plan_summary, query_framework, query_shape) topk(1, max_over_time(slow_queries_info[$__range])) by (query_hash)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Queries Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(slow_queries_duration_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m])",
     "legendFormat": "{{ns}} - {{query_hash}}"
    }
   ]
  },
  {
   "title": "Slow Queries Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(slow_queries_duration_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m])/rate(slow_queries_count_total{job=~\"$job\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m])",
     "legendFormat": "{{ns}} - {{query_hash}}"
    }
   ]
  },
  {
   "title": "Slow Queries Efficiency",
   "type": "timeseries",
   "description": "More Is Better",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(slow_queries_nreturned_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m]) / rate(slow_queries_docs_examined_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m]) < +Inf",
     "legendFormat": "{{ns}} - {{query_hash}}"
    }
   ]
  },
  {
   "title": "Slow Queries Index Efficiency",
   "type": "timeseries",
   "description": "More Is Better",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(slow_queries_keys_examined_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m]) / rate(slow_queries_docs_examined_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m]) < +Inf",
     "legendFormat": "{{ns}} - {{query_hash}}"
    }
   ]
  },
  {
   "title": "Slow Queries Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(slow_queries_count_total{job=~\"$job\", instance=~\"$instance\", ns=~\"$ns\", query_hash=~\"$query_hash\" }[1m])",
     "legendFormat": "{{ns}} - {{query_hash}}"
    }
   ]
  }
 ]
}